### ISSUE TITLE
Dependency on a deprecated R package

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/paper-depression-brouwer-simulation-ATD#6]
The file `extract_simulation_results.R` depends on a deprecated package:

https://github.com/asreview/paper-depression-brouwer-simulation-ATD/blob/094d2c9623119d98a1a9a30fb4bd3cf60f7d7f9c/scripts/extract_simulation_results.R#L6

@JTeijema Can you add the underlying R-scripts to the folder `/scripts` and adjust the code so that it runs without the package?

**Comment by JTeijema** [comment]
Solved in #8 !
